### ISSUE TITLE
创建项目报错

### ISSUE THREAD

**Issue by songliqiang520** [yuyu1987/pithy-test#1]
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\pithy\cli\init.py", line 29, in generate_project
    render_template(jinja_env, template, target_full_name, project_name=project_name)
  File "c:\program files (x86)\python36-32\lib\site-packages\pithy\cli\utils.py", line 69, in render_template
    f.write(content)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\pithy-cli.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\pithy\cli\__init__.py", line 46, in init
    generate_project(project_name, project_type)
  File "c:\program files (x86)\python36-32\lib\site-packages\pithy\cli\init.py", line 35, in generate_project
    raise Exception
Exception

**Comment by yuyu1987** [comment]
@songliqiang520 已修复，可以使用
`pip install -U pithy-test` 更新一下

**Comment by songliqiang520** [comment]
ok,Thank you very much.
